# General Jekyll Config
highlighter: rogue
name: Isfar Here
description: My journey so far
url: "https://isfarbaset19.github.io/"
lsi: false

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Build setting
markdown: kramdown
theme: jekyll-theme-cayman
